name: cv-final-cu114
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - opencv
  - pillow
  - imageio
  - imageio-ffmpeg
  - trimesh
  - pyyaml
  - tqdm
  - ninja
  - cmake
  - pip:
      - wandb
      - swanlab
      - plyfile
      - tyro
      - einops
      - hydra-core
      - omegaconf
      - open3d
